from colorama import init
from colorama import Back
init(autoreset=True)
print('13' +Back.LIGHTWHITE_EX +'                                 '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '       ')
print('12' +Back.LIGHTWHITE_EX +'                              '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '          ')
print('11' +Back.LIGHTWHITE_EX +'                           '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '             ')
print('10' +Back.LIGHTWHITE_EX +'                        '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '                ')
print('9 '  +Back.LIGHTWHITE_EX +'                     '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '                   ')
print('8 '  +Back.LIGHTWHITE_EX +'                  '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '                      ')
print('7 '  +Back.LIGHTWHITE_EX +'               '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '                         ')
print('6 '  +Back.LIGHTWHITE_EX +'            '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '                            ')
print('5 '  +Back.LIGHTWHITE_EX +'         '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '                               ')
print('4 '  +Back.LIGHTWHITE_EX +'      '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '                                  ')
print('3 '  +Back.LIGHTWHITE_EX +'   '+Back.BLACK + '   '+Back.LIGHTWHITE_EX + '                                     ')
print('2 '  +Back.BLACK + '   '+Back.LIGHTWHITE_EX + '                                        ')
print('1 ' +  Back.LIGHTWHITE_EX + '                                           ')
print('0 ' + '  ' +'1' + '  ' +'2' +'  ' +'3' '  ' +'4' +'  ' +'5'+'  ' +'6'+'  ' +'7' +'  ' +'8' +'  ' +'9'+'  ' +'10' +'  ' +'11' +'  ' +'12' +'  ' +'13')